# To run unit tests and new tests on a pull request on dev environment
name: get test list

on:
  pull_request:
    branches: [main]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: apt-get update && sudo apt-get install -y jq

      - name: Mark Repository as Safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm ci

      - name: List Playwright Tests
        id: list-tests
        run: |
          # Run the Playwright test list command
          test_list=$(npx playwright test --list)

          # Process the output into a JSON array
          test_array=$(echo "$test_list" | jq -R -s 'split("\n") | map(select(length > 0))')

          # Save the array as an output
          echo "TEST_LIST=$test_array" >> $GITHUB_ENV
        env:
          CI: true

      - name: Display Test List
        run: |
          echo "Test list: $TEST_LIST"

      - name: Use Test List
        run: |
          echo "Processing the test array..."
          for test in $(echo $TEST_LIST | jq -r '.[]'); do
            echo "Test: $test"
          done
        env:
          TEST_LIST: ${{ env.TEST_LIST }}
