# To run unit tests and new tests on a pull request on dev environment
name: get test list

on:
  pull_request:
    branches: [main]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Mark Repository as Safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm ci

      - name: Cache Playwright Browsers
        id: cache-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install Playwright Browsers
        if: steps.cache-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: List Playwright Tests
        id: list-tests
        run: |
          # Run the Playwright test list command
          test_list=$(npx playwright test --list)

          # Filter output to include valid test lines starting with '['
          filtered_list=$(echo "$test_list" | grep -E '^\s*\[' | sed 's/^\s*//; s/\s*$//')

          # Convert the filtered output into a JSON array
          json_array=$(echo "$filtered_list" | jq -R -s 'split("\n") | map(select(length > 0))')

          # Debug: Display the JSON array
          echo "JSON array:"
          echo "$json_array"

          # Parse and iterate through the array
          echo "$json_array" | jq -r '.[]' | while read -r test; do
            echo "Processing test: $test"
          done

          # Save the JSON array to GITHUB_OUTPUT
          echo "TEST_LIST=$json_array" >> $GITHUB_OUTPUT

      - name: Use Test List
        run: |
          echo "Using the test list..."

          # Read the JSON array
          test_list='${{ steps.list-tests.outputs.TEST_LIST }}'

          # Parse and iterate through the array
          echo "$test_list" | jq -r '.[]' | while read -r test; do
            echo "Processing test: $test"
          done
