# To run unit tests and new tests on a pull request on dev environment
name: get test list

on:
  pull_request:
    branches: [main]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Mark Repository as Safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm ci

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: List Playwright Tests
        id: list-tests
        run: npx playwright test --list

      - name: Display Test List
        run: |
          echo "Test list: $TEST_LIST"

      - name: Use Test List
        run: |
          echo "Processing the test array..."
          for test in $(echo $TEST_LIST | jq -r '.[]'); do
            echo "Test: $test"
          done
        env:
          TEST_LIST: ${{ env.TEST_LIST }}
