name: Playwright Tests on container
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required to deploy to GitHub Pages 
permissions: 
    contents: write

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
           
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
            target_branch: gh-pages
            build_dir: playwright-report
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}