name: 🔘 Run tests on demand

on:
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      total-run-time-in-mins:
        description: "Total expected run time in minutes"
        required: true
        default: "2"
        type: string

      pw-command-to-execute:
        description: "playwright command to run"
        required: true
        default: "npx playwright test --project='chromium'"
        type: string

      fully-parallel:
        description: "Run tests in fully parallel mode"
        required: false
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

      max-allowed-runners:
        description: "Maximum allowed runners"
        required: false
        default: 20
        type: number

jobs:
  run-tests-on-demand:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      total-run-time-in-mins: ${{ inputs.total-run-time-in-mins }}
      pw-command-to-execute: ${{ inputs.pw-command-to-execute }}
      fully-parallel: ${{ inputs.fully-parallel }}
      max-allowed-runners: ${{ inputs.max-allowed-runners }}
    secrets: inherit
