# To run unit tests and new tests on a pull request on dev environment
name: 🆕 Run only new and updated tests on pull request

on:
  pull_request:
    branches: [main]

jobs:
  touched-test-files:
    runs-on: ubuntu-latest
    name: Touched test files
    permissions:
      pull-requests: read
    outputs:
      tests_to_run: ${{ steps.tests_to_run.outputs.test_files }}
    steps:
      - name: Fetch changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: tests/**/*.{spec.ts,test.ts} # spec or test files only. Not other types of ts files (example page, data or fixtures file).

      - name: List changed test files
        id: tests_to_run
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          tests=""
          for file in ${ALL_CHANGED_FILES}; do
            filename=$(basename "$file")
            echo "$filename was changed"
            tests="$tests $filename"
          done
          echo "--grep input to send: $tests"
          echo "test_files=$tests"  >> "$GITHUB_OUTPUT"

  run-only-touched-tests-on-PR-to-main-in-2-mins:
    needs: touched-test-files
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      total-run-time-in-mins: 2
      pw-command-to-execute: "npx playwright test ${{needs.touched-test-files.outputs.tests_to_run}} --project=chromium"
    secrets: inherit
